### ISSUE TITLE
Extract debian / ruby Docker base images

### ISSUE THREAD

**Issue by dreadwarrior** [casi/flatshare_app#2]
* create dedicated git repository
* each image target should go into dedicated branch in the git repository
* integrate automatic builds in Docker Hub (e.g. casi257/docker)
* configure to build branches (e.g. casi257/docker:debian-stretch, casi257/docker:ruby-2.x.y)

**Comment by casi** [comment]
Done. 
=> [casi/docker](https://github.com/casi/docker)
