### ISSUE TITLE
makefile test or spec?

### ISSUE THREAD

**Issue by notapatch** [casi/flatshare_app#20]
I tried @cameronnorman fabulous makefile and it worked nicely. The only issue I found was running the tests where the readme said to use `make test` but that errors out:

    `make: Nothing to be done for `test'.`

Reading the makefile there is a `make spec` which does work. 

Question: Should we use `make test` or `make spec` - I am happy to update the README or makefile as appropriate?

**Comment by casi** [comment]
Hi @notapatch, thanks for the hint! You're totally right. I think we should use `make test` because of the original rails command `rails test`. Since we use test here, it is more consistent.

**Comment by notapatch** [comment]
My mistake. Turns out that having a command name which is the same as a file/directory is a problem with makefile - it thinks you are running a command against the file/directory. There is a `test` directory in the root of the project which causes this issue.

If you add make test:

```
#makefile
...
test:
	docker-compose -f docker-compose.yml run --rm app sh -c 'RAILS_ENV=test rake'
...
```
And then run `make test` instead of the tests being run you get a text message that everything is up to date:

```
make test
make: `test' is up to date.
```

A work around is that you can run the makefile with a `-B`:

```
make -B test
docker-compose -f docker-compose.yml run --rm app sh -c 'RAILS_ENV=test rake'
```

@cameronnorman would have known this and went with an alternative name `spec`. Even though, as you say, it is misleading with the type of tests being used - minitest.

[Why does make think the target is up to date?](https://stackoverflow.com/questions/3931741/why-does-make-think-the-target-is-up-to-date)

**Comment by cameronnorman** [comment]
Yeah this is a bit of a weird one. I made it spec for that reason and also I am used to using rspec which uses a spec folder. Should we update the README.md to make spec. Sorry ahead of time for my booboo

**Comment by casi** [comment]
Okay, interesting behavior. Thanks @notapatch for working this out! :clap: 

I think this is a minor weak point in Make. That would also mean that a spec directory would cause problems, if I took RSpec instead of Minitest. (Briefly to explain: I know that RSpec is better and offers more test possibilities. But that wasn't on my radar at the time.)

All right, let's change the README.md to spec and maybe a quick note that NOT the RSpec test framework is being used, although you might think so.

**Comment by casi** [comment]
@notapatch you can do this if you like. 🙂

**Comment by notapatch** [comment]
How about making the default command "make" run the spec? That's a convention with Rakefile anyway and we won't have to explain it to the README?

**Comment by casi** [comment]
Ah ok, good. Yeah, that's fine with me. @cameronnorman do you agree?

**Comment by cameronnorman** [comment]
Nice one, I agree
