### ISSUE TITLE
Integrate nginx proxy Docker image in dedicated repository

### ISSUE THREAD

**Issue by dreadwarrior** [casi/flatshare_app#3]
* depends on #2 
* add in dedicated branch in the git repository (e.g. nginx-proxy)
* create Docker Hub automatic build (e.g. casi257/docker:nginx-proxy)

**Comment by casi** [comment]
Done.
=> [casi/docker/nginx-proxy](https://github.com/casi/docker/tree/master/nginx-proxy)
